### ISSUE TITLE
命名おかしい

### ISSUE THREAD

**Issue by kou029w** [turippj/TURIPlibrariesForArduino#3]

**Comment by kou029w** [comment]
命名規則が 🤔 です。
メソッド名LCC、変数名スネークケース、ほか（リポジトリ名も）UCCあたりで統一してはいかがでしょうか。

**Comment by t0kage3** [comment]
現在は基本的には、型名：スネークケース、ローカル変数：LCC、グローバル変数：UCCにしているつもりですが、徹底できていないかもしれません。スタンダードな命名規則がありましたら、そちらに合わせます。

**Comment by kou029w** [comment]
重要な指摘でもないので無視しても構いません。例えば「TURIPserver」は大文字単語と小文字単語ですよね？UCCなら「TuripServer」などになるかと思うのです。「cl_TURIPserver」 とかはスネークケースと大文字単語と小文字単語の混在ですよね？「cl_」の有無とは？あとは「cl_TURIPserver::getSizeofPort()」のofだけ小文字なところや「In」「on」などが表記が混在しているところなど。

何を正とするかはお任せします。何がスタンダードか分かんないです。命名規則もドキュメントにしとくとよろしいかとおもいました。

**Comment by kou029w** [comment]
有名どころなら GNU Coding Standards などでしょうか。（よく知らない）

**Comment by kou029w** [comment]
C++なら Google C++ Style Guide とかでしょうか。（これもよく知らない）

**Comment by kou029w** [comment]
Arduinoの場合、このあたりが参考になるのかもしれませんね。
http://qiita.com/loonaifactory/items/1ddf0ec394ed42285b1b

**Comment by kou029w** [comment]
Matzは言いました。「名前重要」と。（？）

**Comment by t0kage3** [comment]
助言ありがとうございます。
/docs ディレクトリ下でドキュメントを作成中です。反映までもうしばしお待ちを。多分今週中にはできるハズ。

**Comment by kou029w** [comment]
別に急いでないです。Qiitaの記事を参考に既存のArduinoライブラリと合わせたほうが良いかと思いました。なんとなくコードが読みにくかったので。

**Comment by t0kage3** [comment]
コメントもあまり無いですしね・・・。
コードどころかライブラリの構成も少々複雑で、UMLの導入も進めています。（こちらはこちらで肥溜めみたいな状況ですがw）
Qiitaの記事は、記法というよりはライブラリのフロントエンドのお話っぽいですね。ポインタは確かに避けたい所ですが、コンセプト（グローバル変数をポートに紐付けする）的にちょっと厳しいかも。

**Comment by t0kage3** [comment]
新しく生やしたbranchに仕様書の書きかけを追加しました。

**Comment by kou029w** [comment]
読みました。クラスや*体は、型ではないと思います。あと先頭だけスネークケースわりにくくないでしょうか？整数はintもlongも同じ表記なのでしょうか？そもそも型を表す名前を付ける意味とは？型が一致しなければコンパイラが警告してくれるはずなので、間違えようが無いようにおもうのですが。あとクラスとかはHogeClassくらいわかりやすいほうがいいとおもいました。
今度 Pull request 作成したらもう少しじっくり読みます。
命名については「慣例に従う」も可。現状、独特な表記が多すぎでは。

**Comment by kou029w** [comment]
めんどうなら「命名規則がないのが規則」と主張すればよい

**Comment by kou029w** [comment]
名前付け
http://qiita.com/Koki_jp/items/f3d3e824f98d182d4100
参考文献も含めて、この記事は役に立ちました

**Comment by t0kage3** [comment]
ありがとうございます。
システムハンガリアンとか使ってますねー。
動詞のリストも助かります。

**Comment by kou029w** [comment]
優先度低そうなのでクローズします
