### ISSUE TITLE
ライブラリが複雑

### ISSUE THREAD

**Issue by kou029w** [turippj/TURIPlibrariesForArduino#4]
ライブラリを整理

- [x] 設計を文書化 (コメントなどでも可)
  - https://github.com/turippj/TURIP
- [x] 動作確認済みのボードとか明記
  - https://github.com/turippj/TURIPlibrariesForArduino/pull/13 にてコンパイル可能なボードを明記
- [x] include一回で利用可能なようにする
- [x] keywords.txt
- [x] example
  - https://github.com/turippj/TURIPlibrariesForArduino/blob/df90686ae831d906a1383287d7f957e32b0a34db/examples/TURIPbridge/TURIPbridge.ino
- [x] releasesあたりにArduino IDE のインポート用のzip置く
- [x] #3

経緯 https://github.com/turippj/TURIPlibrariesForArduino/issues/3#issuecomment-263588002

**Comment by kou029w** [comment]
リストは自分が思いついたものなので、(本Issueのクローズを含め、)適宜変更してください。

**Comment by kou029w** [comment]
説明文を更新しました

**Comment by t0kage3** [comment]
ちょっと、いや、かなり適当な感じですが、一段落したのでReleaseしました。
複数のライブラリが含まれているので、zipのまとめ方がこれで良いのかちょっと怪しい気がしますが・・・。

**Comment by t0kage3** [comment]
一旦クローズします。またツッコミがあれば、またお知らせ下さいませ。
